trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrLoginServer: 'septestcontainerrepo.azurecr.io'
  imageName: 'simple-nginx'

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    containerRegistry: 'sepserviceconnection'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'sepserviceconnection'
    imageName: '$(acrLoginServer)/$(imageName):$(Build.BuildId)'

- task: Docker@2
  displayName: 'Push Docker image to ACR'
  inputs:
    command: 'push'
    containerRegistry: 'sepserviceconnection'
    imageName: '$(acrLoginServer)/$(imageName):$(Build.BuildId)'
